name: Build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
jobs:
  Vitepress_build:
    runs-on: ubuntu-latest
    name: Vitepress build
    steps:
    - uses: actions/checkout@v2
    # - uses: Klemensas/action-autotag@stable
    #   with:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #     tag_prefix: "v"
    # - name: Setup and build
    #   shell: bash
    #   run: |
    #     npm install
    #     npm run build:docs
    #     ls
    #     echo 'finish build'
    #     cd dist
    #     ls
    #     echo 'finish cd'
    #     cat index.html
    #     touch .nojekyll
    #     # git config --global user.email "1208097313@qq.com"
    #     # git config --global user.name "github-actions[bot]"
    #     # git init
    #     # git add -A
    #     # git commit -m autobuild
    #     # git push -f https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git master:gh-pages
    # - uses: JS-DevTools/npm-publish@v1
    #   with:
    #     token: ${{ secrets.NPM_TOKEN }}
    - name: Setup Node.js and pnpm
      uses: actions/setup-node@v3
      with:
          node-version: '20.10.0' # 设置 nodejs 的版本
          
    - name: Install pnpm
      run: npm install -g pnpm # 全局安装 pnpm

    - name: Install dependencies
      run: pnpm install # 使用 pnpm 安装依赖

    - name: Build VitePress
      run: pnpm run build:docs # 这里是打包 vitepress 命令

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 这一步很重要，单独看下面的大步骤，主要是用来给该脚本一些仓库权限
          publish_dir: dist # 指定该文件夹中的 dist 
          publish_branch: gh-pages # 推送到关联仓库的 gh-pages 分支
          dotfiles: true  # 包括在提交中，即使被 .gitignore 文件忽略

